### ISSUE TITLE
Either example from purify-ts 0.16.1 does not compile in TS 4.2.3 

### ISSUE THREAD

**Issue by GrumpyLittleTed** [gigobyte/purify#338]
The example from Either alt https://gigobyte.github.io/purify/adts/Either#alt does not compile in TS 4.2.3 

error TS2345: Argument of type 'Either<string, number>' is not assignable to parameter of type 'Either<never, number>'.
  Type 'string' is not assignable to type 'never'.

**Comment by gigobyte** [comment]
I think that's fine, the purpose of the docs is to show the behaviour of the methods, the example doesn't compile only because the values are inline, not because the example is broken.
